language: node_js
sudo: false

os:
  - linux

node_js:
  - 7.6.0
  - 8.9.0

cache:
  yarn: true
  directories:
    - node_modules

script:
  - npm test

after_script:
  - nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
